MODE: "semantic"
BACKBONE: "segformer"


DATASET:
  dataset: cityscapes
  dataset_folder: "/home/pod/shared-nvme/uv_data/beijing"
  num_workers: 8
  target: "semantic"
  norm: True
  crop_size: [1024, 1024]
  num_classes: 19
  ignore_index: 255
  avoid_index: -1


MODEL:
  input_dim: 10
  encoder_widths: [ 64,64,64,128 ]
  decoder_widths: [ 32,32,64,128 ]
  out_conv: [ 32, 20 ]
  str_conv_k: 4
  str_conv_s: 2
  str_conv_p: 1
  agg_mode: "att_group"
  encoder_norm: "group"
  n_head: 16
  d_model: 256
  d_k: 4
  encoder: False
  return_maps: False
  pad_value: 0
  padding_mode: "reflect"


PIPELINE:
  train:
    epochs: 100
    rdm_seed: null
    display_step: 20
    val_every: 1
    val_after: 0
    save_total_limit: 5

PATH:
  ds_config: "config/ds_config/uvmamba_ds_config_beijing.json"
  res_dir: "result/segformer_beijing"